apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: myforum-frontend:latest
          imagePullPolicy: Never # utilise l'image locale minikube
          ports:
            - containerPort: 80
