apiVersion: v1
kind: Secret
metadata:
  name: myforum-secrets
type: Opaque
stringData:
  # stringData permet de mettre les valeurs en clair (K8s les encode en base64 automatiquement)
  MONGODB_URI: "mongodb+srv://..."
  JWT_SECRET: "ton_secret"
  FRONTEND_URL: "http://localhost"
